-- FIRST_VALUE Y LAST_VALUE ( PRIMER VALOR Y ÚLTIMO)
SELECT 
  titulo,
  FIRST_VALUE(titulo) OVER (ORDER BY popularidad DESC ) AS MasPopular,
  
  LAST_VALUE(titulo) OVER (ORDER BY popularidad DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS MenosPopular
FROM canciones;

/* Se ha de poner el OVER( ORDER BY ) , en el caso del LAST VALUE HAY QUE PONER
ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING